try fix "device type cpu does not match device type of out parameter (cuda)" for UVM case
Summary:
X-link: https://github.com/facebookresearch/FBGEMM/pull/2229

When loading checkpoint for UVM tensors, the following error is hit:
```
Exception raised from check_out_type_matches at fbcode/caffe2/torch/csrc/utils/out_types.cpp:44 (most recent call first):\
\
# 2  c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)\
# 3  torch::utils::check_out_type_matches(at::Tensor const&, std::optional<c10::ScalarType>, bool, std::optional<c10::Layout>, std::optional<c10::Device>, bool)\
# 4  0x0000000038f04e38\
# 5  cfunction_call(_object*, _object*, _object*) [clone .__uniq.184329355527600121329097111544311389932] [clone .llvm.15236209090264943580]\
# 6  PyObject_Call\
# 7  _PyEval_EvalFrameDefault\
# 8  method_vectorcall(_object*, _object* const*, unsigned long, _object*) [clone .__uniq.44356567273764464108930774188262547171] [clone .llvm.11358868503970355743]\
# 9  _PyObject_CallFunctionVa...", "timestamp": 1765744696, "errorService": "Mast", "errorCode": 100, "pyCallStack": "Traceback (most recent call last):\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/model_parallel.py\\", line 1023, in _shard_modules_impl\
    module = self._sharder_map[sharder_key].shard(\
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/embedding.py\\", line 1712, in shard\
    return ShardedEmbeddingCollection(\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/embedding.py\\", line 486, in __init__\
    self._create_lookups()\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/embedding.py\\", line 1330, in _create_lookups\
    lookup = sharding.create_lookup()\
             ^^^^^^^^^^^^^^^^^^^^^^^^\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/sharding/rw_sequence_sharding.py\\", line 156, in create_lookup\
    return GroupedEmbeddingsLookup(\
           ^^^^^^^^^^^^^^^^^^^^^^^^\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/embedding_lookup.py\\", line 193, in __init__\
    self._emb_modules.append(self._create_embedding_kernel(config, pg, device))\
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/embedding_lookup.py\\", line 237, in _create_embedding_kernel\
    return BatchedFusedEmbedding(\
           ^^^^^^^^^^^^^^^^^^^^^^\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torchrec/distributed/batched_embedding_kernel.py\\", line 2387, in __init__\
    SplitTableBatchedEmbeddingBagsCodegen(\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/fbgemm_gpu/split_table_batched_embeddings_ops_training.py\\", line 1031, in __init__\
    self._apply_split(\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/fbgemm_gpu/split_table_batched_embeddings_ops_training.py\\", line 3401, in _apply_split\
    apply_split_helper(\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/fbgemm_gpu/split_table_batched_embeddings_ops_training.py\\", line 355, in apply_split_helper\
    torch.zeros(\
  File \\"/packages/aps.ads.icvr/icvr_launcher#link-tree/torch/utils/_device.py\\", line 109, in __torch_function__\
    return func(*args, **kwargs)\
           ^^^^^^^^^^^^^^^^^^^^^\
RuntimeError: device type cpu does not match device type of out parameter (cuda)\
Exception raised from check_out_type_matches at fbcode/caffe2/torch/csrc/utils/out_types.cpp:44 (most recent call first):\
\
``` 

Example failed jobs:
1. SelfLoopFM, failed after preemption.
https://www.internalfb.com/mlhub/pipelines/runs/mast/aps-omnifm_LWB_infra_bundle-788f1e071d?job_attempt=1&version=0&tab=summary&env=PRODUCTION

2. Just using UVM_CACHING, failed after preemption.
https://www.internalfb.com/mlhub/pipelines/runs/mast/aps-LWB_omnifmv4_1028-30_tk1027_H100_EO_emb25_2304b-97dfc51d00?job_attempt=1&version=0&tab=execution_details&env=prod


This is because the following code:
```
                torch.zeros(
                    split.uvm_size,
                    out=torch.ops.fbgemm.new_unified_tensor(
                        # pyre-fixme[6]: Expected `Optional[Type[torch._dtype]]`
                        #  for 3rd param but got `Type[Type[torch._dtype]]`.
                        torch.zeros(1, device=current_device, dtype=dtype),
                        [split.uvm_size],
                        is_host_mapped=uvm_host_mapped,
                    ),
                ),
```
the first `torch.zeros()` doesn't set `current_device` and will be on `cpu`. but the `torch.ops.fbgemm.new_unified_tensor` has `current_device` set to `cuda`. this caused the device mismatch.

Reviewed By: dharakk

Differential Revision: D89153481