Fix split_embeddings_utils in CMake (#3974)
Summary:
Pull Request resolved: https://github.com/pytorch/FBGEMM/pull/3974

X-link: https://github.com/facebookresearch/FBGEMM/pull/1060

Usage of `get_infos_metadata` in CPU package causes error:
```
NotImplementedError: fbgemm::get_infos_metadata: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl. Please see the following for next steps:  https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html
```

This is because `src/split_embeddings_utils/split_embeddings_utils.cpp` which contains meta registration is not included in CPU build in Cmake.

Reviewed By: q10

Differential Revision: D73150650